Repository dso-toolkit/dso-toolkit, pull requests merged in 2023-10, with the labels that each got.

#2354 #2353 docusaurus toon versies in navigatie
  CHANGELOG.md
  website/docusaurus.config.js
  website/src/css/custom.scss
Labels: 📚 docs

#2371 #2368 selectable styling aanpassingen
  CHANGELOG.md
  packages/core/src/components/selectable/selectable.scss
Labels: 🐛 bug

#2375 #2358 [Fixed] Form group: Table overflow in rich content
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/form-group.scss
Labels: 🐛 bug

#2378 #2373 [Fixed] Legend: teveel witruimte onder filter titel
  CHANGELOG.md
  packages/dso-toolkit/src/components/fieldset/fieldset.scss
Labels: 🐛 bug

#2395 #2388 [Added] Graphics: Foutmelding
  CHANGELOG.md
  packages/dso-toolkit/assets/graphics/foutmelding.svg
  website/docs/fundament/illustraties.mdx
Labels: ⤵️ change

#2406 #2399 [Docs] Logo: Documenteer afgesproken waardes van het ribbon att…
  CHANGELOG.md
  packages/core/src/components.d.ts
  packages/core/src/components/logo/logo.tsx
  packages/core/src/components/logo/readme.md
  website/blog/2023-10-17-dso-toolkit-61.0.0.mdx
Labels: 📚 docs

#2413 #2412 [Docs] Storybook: vervang 'lorem ipsum' door meer echt lijkende…
  CHANGELOG.md
  storybook/src/example-pages/Patronen/zoeken-in-lijst-cards.content.ts
  storybook/src/example-pages/Patronen/zoeken-in-lijst-cards.ts
  storybook/src/example-pages/componenten/application-heading/application-heading-alleen-subtitle-en-step.ts
  storybook/src/example-pages/componenten/application-heading/application-heading-alleen-subtitle.ts
  storybook/src/example-pages/componenten/application-heading/application-heading-met-subtitle-en-step.ts
  storybook/src/example-pages/componenten/application-heading/application-heading-met-subtitle.ts
  storybook/src/example-pages/componenten/application-heading/application-heading.ts
  storybook/src/example-pages/toepassingen/samenwerken/samenwerking-gegevens.content.ts
Labels: 📚 docs

#2407 #2377 [Docs] Readme: Verwijs naar de juiste dso.css
  CHANGELOG.md
  README.md
Labels: 📚 docs

#2396 #2334 [Added] Header: "Help"-button toevoegen
  CHANGELOG.md
  angular-workspace/components/header/header.angular-template.ts
  packages/core/src/components.d.ts
  packages/core/src/components/header/header.interfaces.ts
  packages/core/src/components/header/header.scss
  packages/core/src/components/header/header.tsx
  packages/core/src/components/header/readme.md
  packages/dso-toolkit/src/components/header/header.args.ts
  packages/dso-toolkit/src/components/header/header.models.ts
  packages/dso-toolkit/src/components/header/header.stories-of.ts
  packages/react/src/components/header/header.react-template.tsx
  storybook/cypress/e2e/header.cy.ts
  storybook/src/components/header/header.core-template.ts
  storybook/src/example-pages/Patronen/beheer-basis.content.ts
  storybook/src/example-pages/partials/header.content.ts
  storybook/src/example-pages/toepassingen/regels-op-de-kaart/documenten-VRK.content.ts
  storybook/src/example-pages/toepassingen/regels-op-de-kaart/locatie-overzicht.content.ts
  storybook/src/example-pages/toepassingen/samenwerken/samenwerken-overzicht.content.ts
  storybook/src/example-pages/toepassingen/samenwerken/samenwerking-gegevens.content.ts
Labels: ✨ feature

#2393 #2383 [Changed] highlightbox-banner: aspect ratio aanpassen
  CHANGELOG.md
  packages/core/src/components/highlight-box/highlight-box.scss
  packages/dso-toolkit/src/components/highlight-box/highlight-box.mixins.scss
  packages/dso-toolkit/src/components/highlight-box/highlight-box.scss
  storybook/cypress/e2e/highlight-box.cy.ts
  storybook/src/components/row-equal-heights/row-equal-heights.stories.ts
  storybook/src/example-pages/Patronen/highlight-boxes.ts
  storybook/src/example-pages/Patronen/pagina-met-banner.ts
  storybook/src/example-pages/Patronen/row-equal-heights.ts
  storybook/src/example-pages/toepassingen/aanvragen/landingspagina.ts
  storybook/src/example-pages/toepassingen/loket/helpcentrum.ts
  storybook/src/example-pages/toepassingen/loket/homepage.ts
  storybook/src/example-pages/toepassingen/maatregelen-op-maat/landingspagina.ts
  storybook/src/example-pages/toepassingen/regels-op-de-kaart/landingspagina.ts
  storybook/src/example-pages/toepassingen/vergunningscheck/landingspagina.ts
Labels: ⤵️ change

#2397 #2329 [Fixed] Anchor: Icon no wrap
  CHANGELOG.md
  packages/dso-toolkit/src/components/anchor/anchor.mixins.scss
  packages/dso-toolkit/src/components/anchor/anchor.scss
  packages/dso-toolkit/src/components/banner/banner.scss
  packages/dso-toolkit/src/components/footer/footer.scss
  packages/dso-toolkit/src/components/highlight-box/highlight-box.scss
Labels: 🐛 bug
