Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-04, with the labels that each got.

#2605 #2598 [Fixed] Selectable: Focus outline to include input
  CHANGELOG.md
  packages/core/src/components/selectable/selectable.scss
  packages/dso-toolkit/src/components/selectable/selectable.variables.scss
Labels: 🐛 bug

#2621 #2592 Viewer Grid: MainPanel kunnen verbergen zonder geopend document
  CHANGELOG.md
  packages/core/src/components/viewer-grid/components/main-panel.tsx
  packages/core/src/components/viewer-grid/viewer-grid.scss
  packages/dso-toolkit/src/components/viewer-grid/viewer-grid.args.ts
Labels: ✨ feature

#2578 #2480 Document Component: titel knop mist aria expanded en sluit voor titel tekst
  CHANGELOG.md
  packages/core/src/components/annotation-button/annotation-button.scss
  packages/core/src/components/annotation-output/annotation-output.scss
  packages/core/src/components/document-component/document-component.scss
  packages/core/src/components/document-component/document-component.tsx
Labels: 🐛 bug

#2625 #2557 Autosuggest: Multi row variant
  CHANGELOG.md
  packages/core/src/components/autosuggest/autosuggest.interfaces.ts
  packages/core/src/components/autosuggest/autosuggest.scss
  packages/core/src/components/autosuggest/autosuggest.tsx
  packages/dso-toolkit/src/components/autosuggest/autosuggest.demo.ts
  packages/dso-toolkit/src/components/autosuggest/autosuggest.models.ts
  storybook/src/components/autosuggest/autosuggest.stories.ts
Labels: ✨ feature

#2623 #2561 [Fixed] Document List: Add aria-expanded to dropdown menu example button
  CHANGELOG.md
  storybook/src/components/document-list/document-list.css-template.ts
Labels: 🐛 bug

#2626 #2610 [Fixed] Modal: Vanishes below 768px viewport
  CHANGELOG.md
  packages/core/src/components/modal/modal.tsx
  packages/core/src/components/modal/readme.md
  packages/dso-toolkit/src/components/modal/modal.scss
  packages/dso-toolkit/src/components/modal/readme.md
  website/blog/2024-04-15-dso-toolkit-62.19.0.mdx
  website/blog/authors.yml
Labels: 🐛 bug

#2630 #2627 [Changed] Form Group Files: Remove parts if no files
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/args/form-group-files.args.ts
  packages/dso-toolkit/src/components/form/form-groups/files/form-group-files.scss
  packages/dso-toolkit/src/components/form/form.stories-of.ts
Labels: ⤵️ change

#2632 #2617 [Task] Packages: Dependencies updates
  .github/workflows/danger.yml
  CHANGELOG.md
  Dockerfile
  angular-workspace/package.json
  package.json
  packages/core/package.json
  packages/dso-toolkit/package.json
  packages/react/package.json
  storybook/package.json
  website/docs/voor-maintainers/dependencies-update-procedure.md
  website/package.json
  yarn.lock
Labels: ✅ task

#2637 #2635 [Fixed] Banner: Background image position incorrect
  CHANGELOG.md
  packages/dso-toolkit/src/components/grid/grid.scss
Labels: 🐛 bug

#2647 #2316 Storybook: `storiesOf()` naar CSF
  packages/dso-toolkit/src/components/button/button.stories-of.ts
  packages/dso-toolkit/src/components/button/index.ts
  packages/dso-toolkit/src/components/description/description.content.ts
  packages/dso-toolkit/src/components/description/description.stories-of.ts
  packages/dso-toolkit/src/components/description/index.ts
  packages/dso-toolkit/src/index.ts
  storybook/src/components/button/button.css-stories.ts
  storybook/src/components/button/button.stories.ts
  storybook/src/components/description/description.css-stories.ts
  storybook/src/components/description/description.stories.ts
Labels: ✅ task

#2641 #2282 [Docs] Example Pages: Update steps markup
  CHANGELOG.md
  packages/dso-toolkit/src/components/grid/grid.scss
  storybook/src/example-pages/Patronen/row-equal-heights.ts
  storybook/src/example-pages/toepassingen/aanvragen/landingspagina.ts
  storybook/src/example-pages/toepassingen/maatregelen-op-maat/landingspagina.ts
  storybook/src/example-pages/toepassingen/vergunningscheck/landingspagina.ts
Labels: 📚 docs

#2646 #2616 Form Group Files: Ondersteuning voor een spinner (progess indicator) tijdens upload van bestand
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/content/files.content.ts
  packages/dso-toolkit/src/components/form/form-groups/files/form-group-files.scss
  packages/dso-toolkit/src/components/form/models/form-group-files.model.ts
  storybook/src/components/form/form-group-files.css-template.ts
Labels: ✨ feature
