Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-03, with the labels that each got.

#2590 #2587 Advanced Select: Placeholder toevoegen
  CHANGELOG.md
  packages/core/src/components/advanced-select/advanced-select.models.ts
  packages/core/src/components/advanced-select/advanced-select.scss
  packages/core/src/components/advanced-select/advanced-select.tsx
  packages/dso-toolkit/src/components/advanced-select/advanced-select.content.ts
  packages/dso-toolkit/src/components/advanced-select/advanced-select.models.ts
  packages/dso-toolkit/src/components/advanced-select/advanced-select.variables.scss
Labels: ✨ feature

#2597 Accordion: Remove duplicate colon
  CHANGELOG.md
  storybook/src/components/accordion/accordion.css-template.ts
Labels: 🐛 bug, ♿ accessibility

#2596 #2685 [Fixed] Banner: Fix background color
  CHANGELOG.md
  packages/dso-toolkit/src/components/grid/grid.scss
Labels: 🐛 bug

#2580 #2533 [Changed] Highlight Box: Separate variants
  CHANGELOG.md
  packages/dso-toolkit/src/components/highlight-box/highlight-box.args.ts
  packages/dso-toolkit/src/components/highlight-box/highlight-box.mixins.scss
  packages/dso-toolkit/src/components/highlight-box/highlight-box.models.ts
  packages/dso-toolkit/src/components/highlight-box/highlight-box.scss
  packages/dso-toolkit/src/components/highlight-box/highlight-box.stories-of.ts
  storybook/src/components/highlight-box/highlight-box.core-template.ts
  storybook/src/components/highlight-box/highlight-box.css-template.ts
Labels: ⤵️ change

#2549 #2528 Ozon Content: Ondersteuning voor `<Inhoud wijzigactie="voegtoe|verwijder">`
  CHANGELOG.md
  packages/core/src/components.d.ts
  packages/core/src/components/document-component-demo/document-component.demo.tsx
  packages/core/src/components/document-component/document-component.scss
  packages/core/src/components/document-component/document-component.tsx
  packages/core/src/components/image-overlay/image-overlay.scss
  packages/core/src/components/image-overlay/image-overlay.tsx
  packages/core/src/components/image-overlay/readme.md
  packages/core/src/components/ozon-content/nodes/al.node.tsx
  packages/core/src/components/ozon-content/nodes/figuur.node.tsx
  packages/core/src/components/ozon-content/nodes/inhoud.node.tsx
  packages/core/src/components/ozon-content/nodes/nieuwe-tekst.node.tsx
  packages/core/src/components/ozon-content/nodes/opschrift.node.tsx
  packages/core/src/components/ozon-content/nodes/table.node/table.node.tsx
  packages/core/src/components/ozon-content/nodes/verwijderde-tekst.node.tsx
  packages/core/src/components/ozon-content/ozon-content.scss
  packages/dso-toolkit/src/components/ozon-content/ozon-content.content.ts
  storybook/cypress/e2e/ozon-content.cy.ts
Labels: ✨ feature

#2601 #2552 [Changed] Viewer Grid: Align sizing buttons to top
  CHANGELOG.md
  packages/core/src/components/viewer-grid/viewer-grid.scss
Labels: ⤵️ change

#2577 #2423 Ozon Content: Tabel toevoegingen STOP implementeren inOzon documentweergave
  CHANGELOG.md
  packages/core/src/components/ozon-content/nodes/table.node/colspec/colspec-mapper.ts
  packages/core/src/components/ozon-content/nodes/table.node/colspec/colspec.interface.ts
  packages/core/src/components/ozon-content/nodes/table.node/table-cell.tsx
  packages/core/src/components/ozon-content/nodes/table.node/table.node.tsx
  packages/dso-toolkit/src/components/ozon-content/ozon-content.content.ts
  packages/dso-toolkit/src/components/table/table.mixins.scss
  packages/dso-toolkit/src/components/table/table.scss
Labels: ✨ feature
