Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-05, with the labels that each got.

#2661 #2640 [Changed] Form Group: Errormessage error icon
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/form-group.scss
Labels: ⤵️ change

#2668 #2141 [Fixed] Form: Fix error messages
  CHANGELOG.md
  storybook/src/components/form/form-group-checkboxes.css-template.ts
  storybook/src/components/form/form-group-confirm.css-template.ts
  storybook/src/components/form/form-group-date-picker-legacy.css-template.ts
  storybook/src/components/form/form-group-date-picker.css-template.ts
  storybook/src/components/form/form-group-files.css-template.ts
  storybook/src/components/form/form-group-input.css-template.ts
  storybook/src/components/form/form-group-radios.css-template.ts
  storybook/src/components/form/form-group-search-bar.css-template.ts
  storybook/src/components/form/form-group-select.css-template.ts
  storybook/src/components/form/form-group-textarea.css-template.ts
  website/docs/components/form/index.md
Labels: 🐛 bug

#2659 #2516 Card: Slide Toggle toevoegen
  CHANGELOG.md
  packages/dso-toolkit/src/components/card/card.content.ts
  packages/dso-toolkit/src/components/card/card.models.ts
  packages/dso-toolkit/src/components/card/card.stories-of.ts
  packages/dso-toolkit/src/components/slide-toggle/slide-toggle.models.ts
  storybook/src/components/card/card.core-template.ts
  storybook/src/components/card/card.css-template.ts
  storybook/src/components/slide-toggle/slide-toggle.core-stories.ts
Labels: 📚 docs

#2667 #2650 [Changed] Form Group Files: Remove parts if no files
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/args/form-group-files.args.ts
  packages/dso-toolkit/src/components/form/content/form.content.ts
  packages/dso-toolkit/src/components/form/form.stories-of.ts
  packages/dso-toolkit/src/components/form/readme.md
  storybook/src/components/form/form-group-files.css-template.ts
Labels: ⤵️ change

#2671 #2613 Packages: gulp updaten naar ^5.0.0
  CHANGELOG.md
  packages/dso-toolkit/package.json
  yarn.lock
Labels: ✅ task

#2674 #2658 [Fixed] Tooltip: Long words overflow box
  CHANGELOG.md
  packages/core/src/components/tooltip/tooltip.scss
Labels: 🐛 bug
