Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-09, with the labels that each got.

#2787 #2786 [Fixed] Form: Separation between fieldsets
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/content/form.content.ts
  packages/dso-toolkit/src/components/form/form-group-collection.scss
  packages/dso-toolkit/src/components/form/form.args.ts
  packages/dso-toolkit/src/components/form/form.models.ts
  packages/dso-toolkit/src/components/form/form.stories-of.ts
  packages/dso-toolkit/src/components/form/models/form.model.ts
  packages/dso-toolkit/src/index.ts
  storybook/cypress/fixtures/image-snapshot-components.json
  storybook/src/components/form/form.css-template.ts
  website/blog/2024-09-02-dso-toolkit-64.0.0.mdx
Labels: 🐛 bug

#2740 #2724 [Task] Sass: Deprecation warning mixed declarations
  CHANGELOG.md
  packages/dso-toolkit/src/components/accordion/accordion-theme-compact.scss
  packages/dso-toolkit/src/components/alert/alert.scss
  packages/dso-toolkit/src/components/attachments-counter/attachments-counter.scss
  packages/dso-toolkit/src/components/breadcrumbs/breadcrumbs.mixins.scss
  packages/dso-toolkit/src/components/button/button.mixins.scss
  packages/dso-toolkit/src/components/context/context.scss
  packages/dso-toolkit/src/components/definition-list/definition-list.scss
  packages/dso-toolkit/src/components/delete/delete.mixins.scss
  packages/dso-toolkit/src/components/description/description.scss
  packages/dso-toolkit/src/components/document-header/document-header.scss
  packages/dso-toolkit/src/components/dropdown-menu/dropdown-menu.mixins.scss
  packages/dso-toolkit/src/components/dropdown-menu/dropdown-menu.scss
  packages/dso-toolkit/src/components/footer/footer.scss
  packages/dso-toolkit/src/components/form-control/form-control.mixins.scss
  packages/dso-toolkit/src/components/form/form-buttons/form-buttons.scss
  packages/dso-toolkit/src/components/form/form-group-collection.scss
  packages/dso-toolkit/src/components/form/form-group.scss
  packages/dso-toolkit/src/components/form/form-groups/select/form-group-select.scss
  packages/dso-toolkit/src/components/grid/grid.scss
  packages/dso-toolkit/src/components/highlight-box/highlight-box.scss
  packages/dso-toolkit/src/components/info-button/info-button.mixins.scss
  packages/dso-toolkit/src/components/info/info.scss
  packages/dso-toolkit/src/components/insert/insert.mixins.scss
  packages/dso-toolkit/src/components/label/label.mixins.scss
  packages/dso-toolkit/src/components/link-list/link-list.mixins.scss
  packages/dso-toolkit/src/components/link-list/link-list.scss
  packages/dso-toolkit/src/components/list-button/list-button.mixins.scss
  packages/dso-toolkit/src/components/modal/modal.mixins.scss
  packages/dso-toolkit/src/components/modal/modal.scss
  packages/dso-toolkit/src/components/navbar/navbar.mixins.scss
  packages/dso-toolkit/src/components/search-bar/search-bar.scss
  packages/dso-toolkit/src/components/shopping-cart/shopping-cart.scss
  packages/dso-toolkit/src/components/tabs/tabs.scss
  packages/dso-toolkit/src/components/viewer-grid/viewer-grid.scss
  packages/dso-toolkit/src/di.scss
  packages/dso-toolkit/src/global/mixins/set-colors.mixin.scss
Labels: ✅ task

#2793 #2783 [Task] Packages: Dependencies updates
  CHANGELOG.md
  Dockerfile
  angular-workspace/package.json
  package.json
  packages/core/package.json
  packages/dso-toolkit/package.json
  packages/react/package.json
  storybook/package.json
  website/package.json
  yarn.lock
Labels: ✅ task

#2807 #2806 [Fixed] Mark Bar: Pointer on empty field button
  CHANGELOG.md
  packages/core/src/components/mark-bar/mark-bar.scss
Labels: 🐛 bug

#2796 #1988 [Task] Build: AXE verwerken in buildstraat voor toegankelijkheid componenten
  CHANGELOG.md
  packages/dso-toolkit/src/components/card-container/card-container.args.ts
  packages/dso-toolkit/src/components/card-list/card-list.args.ts
  packages/dso-toolkit/src/components/card/card.args.ts
  packages/dso-toolkit/src/components/card/card.models.ts
  packages/dso-toolkit/src/components/card/card.stories-of.ts
  storybook/cypress.config.ts
  storybook/cypress/e2e/accordion.cy.ts
  storybook/cypress/e2e/action-list.cy.ts
  storybook/cypress/e2e/advanced-select.cy.ts
  storybook/cypress/e2e/alert.cy.ts
  storybook/cypress/e2e/annotation.cy.ts
  storybook/cypress/e2e/autosuggest.cy.ts
  storybook/cypress/e2e/card.cy.ts
  storybook/cypress/e2e/date-picker-legacy.cy.ts
  storybook/cypress/e2e/date-picker.cy.ts
  storybook/cypress/e2e/dropdown-menu.cy.ts
  storybook/cypress/e2e/expandable.cy.ts
  storybook/cypress/e2e/header.cy.ts
  storybook/cypress/e2e/helpcenter-panel.cy.ts
  storybook/cypress/e2e/image-overlay.cy.ts
  storybook/cypress/e2e/image-snapshot-components.cy.ts
  storybook/cypress/e2e/label.cy.ts
  storybook/cypress/e2e/legend-item.cy.ts
  storybook/cypress/e2e/list-button.cy.ts
  storybook/cypress/e2e/logo.cy.ts
  storybook/cypress/e2e/map-controls.cy.ts
  storybook/cypress/e2e/mark-bar.cy.ts
  storybook/cypress/e2e/modal.cy.ts
  storybook/cypress/e2e/ozon-content.cy.ts
  storybook/cypress/e2e/pagination.cy.ts
  storybook/cypress/e2e/panel.cy.ts
  storybook/cypress/e2e/progress-indicator.cy.ts
  storybook/cypress/e2e/selectable.cy.ts
  storybook/cypress/e2e/slide-toggle.cy.ts
  storybook/cypress/e2e/table.cy.ts
  storybook/cypress/e2e/toggletip.cy.ts
  storybook/cypress/e2e/tooltip.cy.ts
  storybook/cypress/e2e/tree-view.cy.ts
  storybook/cypress/e2e/viewer-grid.cy.ts
  storybook/cypress/support/commands.ts
  storybook/src/components/card/card.core-template.ts
  storybook/src/components/card/card.css-template.ts
Labels: ✅ task

#2795 #2758 [Added] Pagination: Navigatie element toevoegen
  CHANGELOG.md
  packages/core/src/components/pagination/pagination.scss
  packages/core/src/components/pagination/pagination.tsx
  packages/dso-toolkit/src/components/pagination/pagination.mixins.scss
  packages/dso-toolkit/src/components/pagination/pagination.scss
  storybook/cypress/e2e/pagination.cy.ts
  storybook/src/components/pagination/pagination.css-template.ts
  website/blog/2024-09-10-dso-toolkit-65.0.0.mdx
Labels: ✨ feature

#2805 #2800 [Docs] Button row: No block margin
  CHANGELOG.md
  storybook/src/example-pages/toepassingen/aanvragen/activiteiten.ts
Labels: 📚 docs
