Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-07, with the labels that each got.

#2712 #2690 Alert: variant `compact`
  CHANGELOG.md
  angular-workspace/components/alert/alert.angular-template.ts
  packages/core/src/components.d.ts
  packages/core/src/components/alert/alert.scss
  packages/core/src/components/alert/alert.tsx
  packages/core/src/components/alert/readme.md
  packages/dso-toolkit/src/components/alert/alert.args.ts
  packages/dso-toolkit/src/components/alert/alert.mixins.scss
  packages/dso-toolkit/src/components/alert/alert.models.ts
  packages/dso-toolkit/src/components/alert/alert.scss
  packages/dso-toolkit/src/components/alert/alert.variables.scss
  packages/dso-toolkit/src/variables/states.scss
  packages/react/src/components/alert/alert.react-template.tsx
  storybook/cypress/e2e/alert.cy.ts
  storybook/src/components/alert/alert.core-template.ts
  storybook/src/components/alert/alert.css-template.ts
Labels: ✨ feature

#2717 #2714 [Changed] Stylelint: Hele repository linten
  .stylelintignore
  CHANGELOG.md
  package.json
  packages/dso-toolkit/src/components/accordion/accordion.scss
  packages/dso-toolkit/src/components/alert/alert.mixins.scss
  packages/dso-toolkit/src/components/badge/badge.mixins.scss
  packages/dso-toolkit/src/components/banner/banner.mixins.scss
  packages/dso-toolkit/src/components/blockquote/blockquote.scss
  packages/dso-toolkit/src/components/breadcrumbs/breadcrumbs.mixins.scss
  packages/dso-toolkit/src/components/button/button.mixins.scss
  packages/dso-toolkit/src/components/card/card.mixins.scss
  packages/dso-toolkit/src/components/code/code.scss
  packages/dso-toolkit/src/components/description/description.mixins.scss
  packages/dso-toolkit/src/components/document-component-list/document-component-list.scss
  packages/dso-toolkit/src/components/document-header/document-header.scss
  packages/dso-toolkit/src/components/document-list/document-list.scss
  packages/dso-toolkit/src/components/dropdown-menu/dropdown-menu.mixins.scss
  packages/dso-toolkit/src/components/dropdown-menu/dropdown-menu.scss
  packages/dso-toolkit/src/components/form-control/form-control.mixins.scss
  packages/dso-toolkit/src/components/form/form-group.scss
  packages/dso-toolkit/src/components/form/form-groups/files/form-group-files.scss
  packages/dso-toolkit/src/components/highlight-box/highlight-box.mixins.scss
  packages/dso-toolkit/src/components/info/info.mixins.scss
  packages/dso-toolkit/src/components/input/input.scss
  packages/dso-toolkit/src/components/label/label.mixins.scss
  packages/dso-toolkit/src/components/list-button/list-button.mixins.scss
  packages/dso-toolkit/src/components/list-button/list-button.scss
  packages/dso-toolkit/src/components/list/list.scss
  packages/dso-toolkit/src/components/modal/modal.mixins.scss
  packages/dso-toolkit/src/components/navbar/navbar.mixins.scss
  packages/dso-toolkit/src/components/pagination/pagination.mixins.scss
  packages/dso-toolkit/src/components/preformatted-text/preformatted-text.scss
  packages/dso-toolkit/src/components/progress-indicator/progress-indicator.mixins.scss
  packages/dso-toolkit/src/components/rich-content/rich-content.mixins.scss
  packages/dso-toolkit/src/components/search-bar/search-bar.scss
  packages/dso-toolkit/src/components/selectable/selectable.mixins.scss
  packages/dso-toolkit/src/components/shopping-cart/shopping-cart.scss
  packages/dso-toolkit/src/components/table/table.scss
  packages/dso-toolkit/src/components/tabs/tabs.scss
  packages/dso-toolkit/src/components/tile/tile.mixins.scss
  packages/dso-toolkit/src/components/viewer-grid/viewer-grid.scss
  packages/dso-toolkit/src/components/whitebox/whitebox.mixins.scss
  packages/dso-toolkit/src/global/functions/contrast-color.functions.scss
  packages/dso-toolkit/src/global/mixins/set-colors.mixin.scss
  packages/dso-toolkit/src/global/mixins/symbol.mixins.scss
  packages/dso-toolkit/src/legacy/legacy-panel.scss
  website/src/components/StorybookComponent/styles.module.scss
  website/src/components/VersionSelector/styles.module.scss
  website/src/css/custom.scss
Labels: ⤵️ change

#2722 #2721 [Fixed] Form Buttons: Button stretches within container
  CHANGELOG.md
  packages/dso-toolkit/src/components/justify-form-groups/justify-form-groups.scss
Labels: 🐛 bug

#2725 #2699 [Changed] Button Secondary: Hover and active state
  CHANGELOG.md
  packages/dso-toolkit/src/components/button/button.mixins.scss
  packages/dso-toolkit/src/components/button/button.variables.scss
  packages/dso-toolkit/src/variables/colors.scss
  website/docs/fundament/kleuren.mdx
  website/src/components/ColorSwatch/styles.module.scss
Labels: ⤵️ change

#2730 #2711 Panel: New component
  CHANGELOG.md
  packages/core/src/components.d.ts
  packages/core/src/components/icon/readme.md
  packages/core/src/components/panel/panel.scss
  packages/core/src/components/panel/panel.tsx
  packages/core/src/components/panel/readme.md
  packages/dso-toolkit/src/components/panel/index.ts
  packages/dso-toolkit/src/components/panel/panel.args.ts
  packages/dso-toolkit/src/components/panel/panel.models.ts
  packages/dso-toolkit/src/components/panel/panel.stories-of.ts
  packages/dso-toolkit/src/index.ts
  storybook/cypress/e2e/panel.cy.ts
  storybook/src/components/panel/panel.core-stories.ts
  storybook/src/components/panel/panel.core-template.ts
  storybook/src/templates.ts
Labels: ✨ feature

#2734 #2726 [Fixed] Logo: Remove aria label
  CHANGELOG.md
  packages/core/src/components/logo/logo.tsx
Labels: 🐛 bug

#2729 #2638 Autosuggest: scrollable suggestielijst
  CHANGELOG.md
  packages/core/src/components/autosuggest/autosuggest.scss
  packages/core/src/components/autosuggest/autosuggest.tsx
  packages/core/src/components/autosuggest/autosuggest.variables.scss
  packages/core/src/components/autosuggest/readme.md
  packages/core/src/components/scrollable/readme.md
  packages/core/src/components/viewer-grid/viewer-grid.variables.scss
  packages/dso-toolkit/src/components/autosuggest/autosuggest.demo.ts
  storybook/cypress/e2e/autosuggest.cy.ts
  storybook/src/components/autosuggest/autosuggest.core-stories.ts
Labels: ✨ feature
