Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-08, with the labels that each got.

#2747 #2718 [Task] Packages: Dependencies updates
  .github/workflows/danger.yml
  CHANGELOG.md
  Dockerfile
  angular-workspace/package.json
  package.json
  packages/core/package.json
  packages/core/src/components/accordion/components/accordion-section.tsx
  packages/dso-toolkit/package.json
  packages/dso-toolkit/src/components/button/button.variables.scss
  packages/react/package.json
  storybook/package.json
  storybook/src/components/selectable/selectable.core-template.ts
  website/docs/voor-maintainers/dependencies-update-procedure.md
  website/package.json
  website/src/functions/versions.function.ts
  yarn.lock
Labels: ✅ task

#2744 #2688 [Added] Build: Artifact integrity
  .gitignore
  CHANGELOG.md
  deploy.sh
  scripts/create-hashes/index.ts
  website/docs/voor-developers/api.mdx
Labels: ✨ feature

#2764 #2631 [Task] Packages: `ESLint` updaten naar v9
  .eslintignore
  .eslintrc.js
  CHANGELOG.md
  angular-workspace/.storybook/main.ts
  eslint.config.mjs
  package.json
  packages/core/src/components/autosuggest/autosuggest.tsx
  packages/core/src/components/date-picker-legacy/date-picker-legacy.tsx
  packages/core/src/components/toggletip/toggletip.tsx
  packages/react/.storybook/main.ts
  packages/react/.storybook/preview.ts
  patches/@stencil-community+eslint-plugin+0.8.0.patch
  storybook/.storybook/main.ts
  storybook/cypress/e2e/date-picker-legacy.cy.ts
  yarn.lock
Labels: ✅ task

#2770 #2765 [Changed] Document Component: Panel implementeren
  CHANGELOG.md
  angular-workspace/components/annotation-button/annotation-button.angular-template.ts
  angular-workspace/components/annotation-output/annotation-output.angular-template.ts
  angular-workspace/templates.ts
  packages/core/src/components.d.ts
  packages/core/src/components/annotation-button/annotation-button.scss
  packages/core/src/components/annotation-button/annotation-button.tsx
  packages/core/src/components/annotation-button/readme.md
  packages/core/src/components/annotation-output/annotation-output.scss
  packages/core/src/components/annotation-output/annotation-output.tsx
  packages/core/src/components/annotation-output/readme.md
  packages/core/src/components/annotation/annotation-locatie/readme.md
  packages/core/src/components/document-component-demo/document-component.demo.tsx
  packages/core/src/components/document-component-demo/readme.md
  packages/core/src/components/document-component/document-component.tsx
  packages/core/src/components/document-component/readme.md
  packages/core/src/components/expandable/readme.md
  packages/core/src/components/icon/readme.md
  packages/core/src/components/panel/readme.md
  packages/core/src/components/responsive-element/readme.md
  packages/core/src/components/slide-toggle/readme.md
  packages/dso-toolkit/src/components/annotation-button/annotation-button.models.ts
  packages/dso-toolkit/src/components/annotation-output/annotation-output.models.ts
  packages/dso-toolkit/src/components/document-component/document-component.stories-of.ts
  packages/dso-toolkit/src/index.ts
  packages/react/src/components/annotation-button/annotation-button.react-template.tsx
  packages/react/src/components/annotation-output/annotation-output.react-template.tsx
  packages/react/src/templates.ts
  storybook/src/components/annotation-button/annotation-button.core-template.ts
  storybook/src/components/annotation-output/annotation-output.core-template.ts
  storybook/src/components/document-component/document-component.core-stories.ts
  storybook/src/components/document-component/document-component.decorator.ts
  storybook/src/templates.ts
Labels: ⤵️ change

#2759 #2701 [Added] Document Component: Asynchroon inladen afbeeldingen zorgt voor instabiele scrollTo() bij afnemer
  CHANGELOG.md
  packages/core/src/components/ozon-content/nodes/figuur.node.tsx
  packages/core/src/components/ozon-content/ozon-content.scss
  packages/dso-toolkit/src/components/document-component/document-component.stories-of.ts
  packages/dso-toolkit/storybook-assets/ozon-response-omgevingsvisie.json
  storybook/cypress/e2e/ozon-content.cy.ts
Labels: ✨ feature

#2767 #2757 [Changed] Files: Change focus state
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/form-groups/files/form-group-files.scss
  packages/dso-toolkit/src/utilities.scss
Labels: ⤵️ change

#2771 #2519 [Deprecated] Input Number: Deprecate component
  CHANGELOG.md
  storybook/cypress/fixtures/image-snapshot-components.json
  storybook/src/components/input-number/input-number.css-stories.ts
  storybook/src/components/input-number/input-number.css-template.ts
Labels: 🪦 deprecate

#2756 #2741 [Changed] Form And Form Group Radios: Update markup
  CHANGELOG.md
  packages/dso-toolkit/src/components/form/form-group-collection.scss
  packages/dso-toolkit/src/components/form/form.args.ts
  packages/dso-toolkit/src/components/form/form.models.ts
  packages/dso-toolkit/src/components/form/form.scss
  packages/dso-toolkit/src/components/form/form.stories-of.ts
  packages/dso-toolkit/src/components/form/models/form.model.ts
  packages/dso-toolkit/src/index.ts
  storybook/src/components/form/form-group-confirm.css-template.ts
  storybook/src/components/form/form-group-radios.css-template.ts
  storybook/src/components/form/form.css-template.ts
  storybook/src/components/form/form.stories.ts
  storybook/src/example-pages/Patronen/zoeken-in-lijst-cards.ts
  storybook/src/example-pages/toepassingen/aanvragen/project.content.ts
  storybook/src/example-pages/toepassingen/aanvragen/verzoeken.ts
  website/blog/2024-08-08-dso-toolkit-63.0.0.mdx
  website/blog/2024-08-20-dso-toolkit-63.0.0.mdx
  website/docs/components/form/index.md
Labels: 💥 BREAKING, ⤵️ change

#2775 #2774 [Changed] Accordion: Badge vervangen met Label
  CHANGELOG.md
  packages/core/src/components.d.ts
  packages/core/src/components/accordion/components/accordion-section.scss
  packages/core/src/components/accordion/components/accordion-section.tsx
  packages/core/src/components/accordion/components/readme.md
  packages/core/src/components/badge/readme.md
  packages/core/src/components/label/label.interfaces.ts
  packages/core/src/components/label/label.tsx
  packages/core/src/components/label/readme.md
  packages/dso-toolkit/src/components/accordion/accordion.args.ts
  packages/dso-toolkit/src/components/accordion/accordion.models.ts
  packages/dso-toolkit/src/components/accordion/accordion.scss
  packages/dso-toolkit/src/components/accordion/accordion.stories-of.ts
  packages/dso-toolkit/src/components/label/label.models.ts
  packages/react/src/components/accordion/accordion.react-template.tsx
  storybook/cypress/e2e/accordion.cy.ts
  storybook/src/components/accordion/accordion.core-template.ts
  storybook/src/components/accordion/accordion.css-template.ts
Labels: ⤵️ change

#2772 #2677 [Task] Packages: `iframe-resizer` new version 5
  CHANGELOG.md
  angular-workspace/.storybook/main.ts
  angular-workspace/package.json
  packages/react/.storybook/main.ts
  packages/react/package.json
  storybook/.storybook/main.ts
  storybook/package.json
  website/package.json
  website/src/components/StorybookComponent/index.tsx
  yarn.lock
Labels: ✅ task

#2780 #2778 [Fixed] List Button: Border color not as per design
  CHANGELOG.md
  packages/dso-toolkit/src/components/list-button/list-button.mixins.scss
Labels: 🐛 bug
