Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-11, with the labels that each got.

#2862 #2851 [Fixed] Dropdown menu: Button icon hover color
  CHANGELOG.md
  packages/dso-toolkit/src/components/dropdown-menu/dropdown-menu.scss
Labels: 🐛 bug

#2852 #2830 [Added] Web Components: Ondersteuning voor meertaligheid
  CHANGELOG.md
  packages/core/package.json
  packages/core/src/components.d.ts
  packages/core/src/components/alert/alert.i18n.ts
  packages/core/src/components/alert/alert.tsx
  packages/core/src/components/autosuggest/autosuggest.i18n.ts
  packages/core/src/components/autosuggest/autosuggest.tsx
  packages/core/src/components/header/header.i18n.ts
  packages/core/src/components/header/header.tsx
  packages/core/src/components/logo/logo.tsx
  packages/core/src/components/logo/readme.md
  packages/core/src/components/map-base-layers/map-base-layers.i18n.ts
  packages/core/src/components/map-base-layers/map-base-layers.tsx
  packages/core/src/components/map-controls/map-controls.i18n.ts
  packages/core/src/components/map-controls/map-controls.tsx
  packages/core/src/components/map-overlays/map-overlays.i18n.ts
  packages/core/src/components/map-overlays/map-overlays.tsx
  packages/core/src/components/modal/modal.i18n.ts
  packages/core/src/components/modal/modal.tsx
  packages/core/src/components/progress-indicator/progress-indicator.i18n.ts
  packages/core/src/components/progress-indicator/progress-indicator.tsx
  packages/core/src/components/progress-indicator/readme.md
  packages/core/src/utils/i18n.ts
  packages/dso-toolkit/src/components/logo/logo.args.ts
  packages/dso-toolkit/src/components/logo/logo.models.ts
  packages/dso-toolkit/src/components/logo/logo.stories-of.ts
  plop-templates/new-stencil-component/stencil-component.i18n.ts.hbs
  plop-templates/new-stencil-component/stencil-component.tsx.hbs
  plopfile.mjs
  storybook/.storybook/i18n.decorator.ts
  storybook/.storybook/preview.ts
  storybook/cypress/e2e/alert.cy.ts
  storybook/cypress/e2e/autosuggest.cy.ts
  storybook/cypress/e2e/i18n.cy.ts
  storybook/cypress/e2e/logo.cy.ts
  storybook/cypress/e2e/map-controls.cy.ts
  storybook/cypress/e2e/modal.cy.ts
  storybook/cypress/e2e/progress-indicator.cy.ts
  storybook/src/components/logo/logo.core-stories.ts
  storybook/src/components/logo/logo.core-template.ts
  website/docs/voor-maintainers/internationalization.md
  yarn.lock
Labels: ✨ feature

#2873 #2746 [Added] Skiplink: New component
  CHANGELOG.md
  packages/core/src/components.d.ts
  packages/core/src/components/icon/readme.md
  packages/core/src/components/skiplink/readme.md
  packages/core/src/components/skiplink/skiplink.interfaces.ts
  packages/core/src/components/skiplink/skiplink.scss
  packages/core/src/components/skiplink/skiplink.tsx
  packages/dso-toolkit/src/components/html/html.scss
  packages/dso-toolkit/src/components/skiplink/index.ts
  packages/dso-toolkit/src/components/skiplink/skiplink.args.ts
  packages/dso-toolkit/src/components/skiplink/skiplink.models.ts
  packages/dso-toolkit/src/components/skiplink/skiplink.stories-of.ts
  packages/dso-toolkit/src/index.ts
  storybook/cypress/e2e/skiplink.cy.ts
  storybook/cypress/support/cypress-styling.ts
  storybook/src/components/skiplink/skiplink.core-stories.ts
  storybook/src/components/skiplink/skiplink.core-template.ts
  storybook/src/example-pages/toepassingen/loket/homepage.ts
  storybook/src/templates.ts
Labels: ✨ feature

#2882 #2874 [Docs] I18n: Documentatie i18n voor maintainers corrigeren
  CHANGELOG.md
  website/docs/voor-maintainers/internationalization.md
Labels: 📚 docs

#2866 #2829 [Fixed] Map Controls: Info no background color
  CHANGELOG.md
  packages/core/src/components/selectable/selectable.scss
  packages/dso-toolkit/src/components/info/info.mixins.scss
Labels: 🐛 bug

#2885 #2863 [Task] Packages: Dependencies updates
  CHANGELOG.md
  Dockerfile
  angular-workspace/package.json
  package.json
  packages/core/package.json
  packages/dso-toolkit/package.json
  packages/react/package.json
  website/package.json
  yarn.lock
Labels: ✅ task

#2890 #2708 [Removed] Input Number, List Button: Verwijder HTML/CSS componenten
  CHANGELOG.md
  packages/core/src/components/list-button/list-button.scss
  packages/core/src/components/list-button/list-button.variables.scss
  packages/dso-toolkit/src/components/form/args/form-group-input-number.args.ts
  packages/dso-toolkit/src/components/form/content/form.content.ts
  packages/dso-toolkit/src/components/form/content/input-number.content.ts
  packages/dso-toolkit/src/components/form/form-groups/input-number/form-group-input-number.scss
  packages/dso-toolkit/src/components/form/form.models.ts
  packages/dso-toolkit/src/components/form/form.scss
  packages/dso-toolkit/src/components/form/form.stories-of.ts
  packages/dso-toolkit/src/components/form/models/form-group-input-number.model.ts
  packages/dso-toolkit/src/components/form/models/form-group.model.ts
  packages/dso-toolkit/src/components/input-number/_index.scss
  packages/dso-toolkit/src/components/input-number/index.ts
  packages/dso-toolkit/src/components/input-number/input-number.args.ts
  packages/dso-toolkit/src/components/input-number/input-number.mixins.scss
  packages/dso-toolkit/src/components/input-number/input-number.models.ts
  packages/dso-toolkit/src/components/input-number/input-number.scss
  packages/dso-toolkit/src/components/input-number/input-number.stories-of.ts
  packages/dso-toolkit/src/components/input-number/readme.md
  packages/dso-toolkit/src/components/list-button/_index.scss
  packages/dso-toolkit/src/components/list-button/list-button.args.ts
  packages/dso-toolkit/src/components/list-button/list-button.mixins.scss
  packages/dso-toolkit/src/components/list-button/list-button.models.ts
  packages/dso-toolkit/src/components/list-button/list-button.scss
  packages/dso-toolkit/src/components/list-button/list-button.stories-of.ts
  packages/dso-toolkit/src/dso.scss
  packages/dso-toolkit/src/index.ts
  storybook/cypress/fixtures/image-snapshot-components.json
  storybook/src/components/form/form-group-input-number.css-template.ts
  storybook/src/components/form/form-group.css-template.ts
  storybook/src/components/form/form.stories.ts
  storybook/src/components/input-number/input-number.css-stories.ts
  storybook/src/components/input-number/input-number.css-template.ts
  storybook/src/components/list-button/list-button.css-stories.ts
  storybook/src/components/list-button/list-button.css-template.ts
  storybook/src/example-pages/toepassingen/aanvragen/activiteiten.content.ts
  storybook/src/templates.ts
  website/docs/components/form/form-group/input-number.mdx
  website/docs/components/form/input-number.mdx
  website/docs/components/form/list-button.mdx
Labels: 🗑️ Remove

#2899 #2898 [Fixed] Styling: styling via attributen (React bindings)
  CHANGELOG.md
  packages/core/src/components/label/label.tsx
  packages/core/src/components/progress-indicator/progress-indicator.tsx
Labels: 🐛 Bug

#2903 #2835 [Added] Document Card: Aanvullende functionaliteit
  CHANGELOG.md
  packages/core/src/components/document-card/document-card.scss
  packages/dso-toolkit/src/components/document-card/document-card.args.ts
  packages/dso-toolkit/src/components/document-card/document-card.models.ts
  packages/dso-toolkit/src/components/document-card/document-card.stories-of.ts
  storybook/cypress/e2e/document-card.cy.ts
  storybook/src/components/document-card/document-card.core-stories.ts
  storybook/src/components/document-card/document-card.core-template.ts
Labels: ✨ Feature
