Repository dso-toolkit/dso-toolkit, pull requests merged in 2024-12, with the labels that each got.

#2888 #2271 [Added] Document Component: type "inhoudsopgave"
  CHANGELOG.md
  packages/core/src/components.d.ts
  packages/core/src/components/document-component-demo/document-component.demo.tsx
  packages/core/src/components/document-component-demo/readme.md
  packages/core/src/components/document-component/document-component-heading.tsx
  packages/core/src/components/document-component/document-component.models.ts
  packages/core/src/components/document-component/document-component.scss
  packages/core/src/components/document-component/document-component.tsx
  packages/core/src/components/document-component/readme.md
  packages/dso-toolkit/src/components/document-component/document-component.args.ts
  packages/dso-toolkit/src/components/document-component/document-component.models.ts
  packages/dso-toolkit/src/components/document-component/document-component.stories-of.ts
  packages/dso-toolkit/src/components/document-component/document-component.variables.scss
  storybook/cypress/e2e/document-component.cy.ts
  storybook/src/components/document-component/document-component.core-stories.ts
  storybook/src/components/document-component/document-component.core-template.ts
Labels: ✨ Feature

#2924 Responsive-element: e2e test schrijven
  CHANGELOG.md
  storybook/cypress/e2e/responsive-element.cy.ts
  storybook/cypress/fixtures/image-snapshot-components.json
Labels: ✅ Task

#2900 #2828 card internalize webcomponent styling
  CHANGELOG.md
  packages/core/src/components/card/card.scss
  packages/core/src/components/document-card/document-card.scss
  packages/core/src/components/plekinfo-card/plekinfo-card.scss
  packages/dso-toolkit/src/components/card/card.scss
  packages/react/src/components/card/card.react-template.tsx
Labels: ✅ Task

#2861 #2365 [Changed] Header: ShadowRoot
  CHANGELOG.md
  packages/core/src/components/header/header.scss
  packages/core/src/components/header/header.tsx
  packages/dso-toolkit/src/components/header/header.scss
  packages/dso-toolkit/src/dso.scss
  storybook/cypress/e2e/header.cy.ts
Labels: ⤵️ Change

#2919 #2303 [Changed] Banner: No dependency on grid system
  CHANGELOG.md
  packages/dso-toolkit/src/components/banner/banner.mixins.scss
  packages/dso-toolkit/src/components/banner/banner.scss
  packages/dso-toolkit/src/components/banner/banner.variables.scss
  storybook/src/components/banner/banner.core-template.ts
  storybook/src/components/banner/banner.css-template.ts
  website/blog/2024-12-16-dso-toolkit-67.2.0.mdx
Labels: ⤵️ Change
